language: node_js

node_js:
  - node
  - lts/boron
  - lts/argon

before_deploy:
  - yarn pack --filename package.tgz

deploy:
  - provider: npm
    email: contact@florentin-dubois.fr
    api_key:
      secure: oMAbEwefd3UQ8hiQlbEO6Fx+m7LZnOSuZIjNHM4/LmlPmdUX4pN/FrbapLsYUB/yNio0duQZKPAs9jVcIWe6TUJlA5UcAUUd74ssl/YWuULsIlv1hH6HmbL7wBhMSgMACIiLLPlw7cHD7l0thRIN2jTXBPD65PY5liGC5EX78hGqCW1LqYgZ2rX1vw54HB6dCpadk+w+UAib6NXUaFIyRnPDAUWFYli+mR8fs/TIyfhxS1uJa1ego5CSXL6CQQ1ZgS2vhX1QDikEDb2C7YhKvXLVowQF4WtlDzdUxSYsjnPCU3kU8CDWqQlTv2xyORe2JnA6KdrUZOM+mylbx7Jhg4XwSeYaHaeWor2zT/zu9XtSS50d/W9LsTAO7Y84oBmYvDxKPhPHJ2H2w7mMmRGaJ4MTm2zpcaitwCmpjvdbXloBmtmOtRzeNxYbTk8YX85AXGyw1AL/M2zkqQ5Wlf8yudVb4MYFaZnWAq+CPjOOezuZnEfdVsLYTwuN1CfjVBlJ8Az5zAH3tMD6o7taeD07uWkNlcBgVCi8IHjGD2KTIieH8kKMCJ0IS0B5+iMxe8KWbvst9MRcwOKCmu13VVxiRXouWBjsECkL6YlPbGB/vPdN1jtd3/oT8yqTMq1JnKgfe76HnFVAZu/BoEvgu7/MC1cq5eZMYfjC3XymfihpD/I=
    on:
      tags: true
      repo: starry-comet/comet-logger

  - provider: releases
    api_key:
      secure: VEeyUPZJiptf6LR9X3RvgLz7QhRvYXO1bk2pap4z5ZgY3kn47t/r3pBoybNAy3UgWmxNzZBEjjLmnxxFsNC6kPSqSnZU7fsn5S1pB0sYLyx1HCFCo0eQnePIoAjAOO7ytlSOieHvE4D3zqhNEmVFneTHtyK0HBmAXI3omT55R6yDmuRPGzg8dVvaflfb6SWXBM0vQ52X/wwEAdLLTp7HTzWqjVF8KkpwnO099zKX3ltHPNAI7MQOsIW+JguZD5vNZehxqInUuONC/J/Wn4BMcN6mGOOkERW8jQMDRYG0j6rdHqrRyUANcF+mtnFOnBFiq/5ZGUG7T77kN7102Jim6rxVCDXlAxVqBY70h0a7RVPcn1/LpdEofMr6WeFDxqYcP6TF+auTCY3oSsQtRcW4Lu65YSOyfmWnoM0gFNMVmaKLAkFS8MedHJyKFbBP6yjZwrKpXhIrwhbiRMeer2WcgxQEp12XBpXF2wlKEF2C9+zjTP5ZoQrmMZxwoi5lc97aWCl/gNs/DNn1mKy2yQI8sdwOyLoxYi9zh32zTC9onjc/fAtF3JLDCbesH97PPdCSVBPtKg2yNuw7j/uEtKNDmHSuuUuZLwx+vxPQR4VE8gqGa+NaUuzJNoomYkff0bU5GJOF6N9bliw2b6RkpWh2OG/XTSGvWBXCcCESXQpu+Hw=

    file: package.tgz
    on:
      repo: starry-comet/comet-logger
      tags: true
